/*
 * L2jFrozen Project - www.l2jfrozen.com 
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA
 * 02111-1307, USA.
 *
 * [URL]http://www.gnu.org/copyleft/gpl.html[/URL]
 */
package com.l2jfrozen.gameserver.handler.admincommandhandlers;

public enum CommandEnum
{
	admin_admin,
	admin_admin1,
	admin_admin2,
	admin_admin3,
	admin_admin4,
	admin_admin5,
	admin_gmliston,
	admin_gmlistoff,
	admin_silence,
	admin_diet,
	admin_set,
	admin_set_menu,
	admin_set_mod,
	admin_saveolymp,
	admin_manualhero,
	admin_list_announcements,
	admin_reload_announcements,
	admin_announce_announcements,
	admin_add_announcement,
	admin_del_announcement,
	admin_announce,
	admin_critannounce,
	admin_announce_menu,
	admin_list_autoannouncements,
	admin_add_autoannouncement,
	admin_del_autoannouncement,
	admin_autoannounce,
	admin_setaio,
	admin_removeaio,
	admin_getbuffs,
	admin_stopbuff,
	admin_stopallbuffs,
	admin_areacancel,
	admin_cache_htm_rebuild,
	admin_cache_htm_reload,
	admin_cache_reload_path,
	admin_cache_reload_file,
	admin_cache_crest_rebuild,
	admin_cache_crest_reload,
	admin_cache_crest_fix,
	admin_start_monitor_char,
	admin_stop_monitor_char,
	admin_block_char_packet,
	admin_restore_char_packet,
	admin_l2jfrozen,
	admin_itemcreate,
	admin_create_item,
	admin_mass_create,
	admin_clear_inventory,
	admin_ctf,
	admin_ctf_name,
	admin_ctf_desc,
	admin_ctf_join_loc,
	admin_ctf_edit,
	admin_ctf_control,
	admin_ctf_minlvl,
	admin_ctf_maxlvl,
	admin_ctf_tele_npc,
	admin_ctf_tele_team,
	admin_ctf_tele_flag,
	admin_ctf_npc,
	admin_ctf_npc_pos,
	admin_ctf_reward,
	admin_ctf_reward_amount,
	admin_ctf_team_add,
	admin_ctf_team_remove,
	admin_ctf_team_pos,
	admin_ctf_team_color,
	admin_ctf_team_flag,
	admin_ctf_join,
	admin_ctf_teleport,
	admin_ctf_start,
	admin_ctf_startevent,
	admin_ctf_abort,
	admin_ctf_finish,
	admin_ctf_sit,
	admin_ctf_dump,
	admin_ctf_save,
	admin_ctf_load,
	admin_ctf_jointime,
	admin_ctf_eventtime,
	admin_ctf_autoevent,
	admin_ctf_minplayers,
	admin_ctf_maxplayers,
	admin_ctf_interval,
	admin_changename, // changes char name
	admin_setname, // changes char name
	admin_edit_character,
	admin_current_player,
	admin_nokarma,
	admin_setkarma,
	admin_character_list, // same as character_info, kept for compatibility purposes
	admin_character_info, // given a player name, displays an information window
	admin_show_characters,
	admin_find_character,
	admin_find_dualbox,
	admin_find_ip, // find all the player connections from a given IPv4 number
	admin_find_account, // list all the characters from an account (useful for GMs w/o DB access)
	admin_save_modifications, // consider it deprecated...
	admin_rec,
	admin_setclass,
	admin_settitle,
	admin_setsex,
	admin_setcolor,
	admin_fullfood,
	admin_remclanwait,
	admin_setcp,
	admin_sethp,
	admin_setmp,
	admin_setchar_cp,
	admin_setchar_hp,
	admin_setchar_mp,
	admin_sethero,
	admin_geo_z,
	admin_geo_type,
	admin_geo_nswe,
	admin_geo_los,
	admin_geo_position,
	admin_geo_bug,
	admin_geo_load,
	admin_geo_unload,
	admin_view_petitions,
	admin_view_petition,
	admin_accept_petition,
	admin_reject_petition,
	admin_reset_petitions,
	admin_pledge,
	admin_server_shutdown,
	admin_server_restart,
	admin_server_abort,
	admin_show_moves,
	admin_show_moves_other,
	admin_show_teleport,
	admin_teleport_to_character,
	admin_teleportto,
	admin_move_to,
	admin_teleport_character,
	admin_recall,
	admin_walk,
	admin_recall_npc,
	admin_gonorth,
	admin_gosouth,
	admin_goeast,
	admin_gowest,
	admin_goup,
	admin_godown,
	admin_instant_move,
	admin_sendhome,
	admin_tele,
	admin_teleto,
	admin_recall_party

}